apiVersion: v1
kind: Template
metadata:
  name: kafkanetes-deploy-kafka-manager
  annotations:
    description: 1-pod Kafka Manager
    tags: messaging,kafka,Manager

parameters:
- name: ZK_HOSTS
  description: Zookeeper host and port
  required: true
  value: localhost:2181
- name: KM_VERSION
  description: Kafka Manager Version
  required: true
  value: kafkanetes-kafka
- name: ZOOKEEPER_SERVICE
  description: DNS name of ZooKeeper service
  required: true
  value: kafkanetes-zk
- name: IMAGESTREAM
  description: Kafkanetes imagestream name
  required: true
  value: kafkanetes

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: kafkanetes
          image: ${IMAGESTREAM}
          command:
          - bin/kafka-server-start.sh
          args:
          - config/server.properties
          - --override
          - zookeeper.connect=${ZOOKEEPER_SERVICE}
          - --override
          - advertised.host.name=${OBJECT_NAME_PREFIX}
          volumeMounts:
          - mountPath: /tmp/kafka-logs
            name: kafka-logs
          ports:
          - containerPort: 9092
        volumes:
        - name: kafka-logs
          persistentVolumeClaim:
            claimName: ${OBJECT_NAME_PREFIX}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - kafkanetes
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 9092
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
